url: https://y7kim.github.io
baseurl: /openlabel

# Site settings
title: OpenLabel
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Luca Attanasio
  pic: 1
  position: Information and Communication Technology
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/luca-attanasio/
    - title: facebook
      url: https://www.facebook.com/luca.attanasio96

- name: Edoardo Chiocchi
  pic: 2
  position: Psicologia di Comunità
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/edoardo-chiocchi-71a5a119a/

- name: Francesca Giovanetti
  pic: 3
  position: Medicina
  social:
    - title: facebook
      url: https://www.facebook.com/francesca.giovanetti.33

- name: Erika Grappiglia
  pic: 4
  position: Giurisprudenza
  social:
    - title: facebook
      url: https://www.facebook.com/erika.grappiglia

- name: Pierfrancesco Golinelli
  pic: 5
  position: Ingegnere meccanico
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/pier-francesco-goli/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty